correct_action = {
    'S11': {
        'Discussion': 'Discussion 1',  
        'Discussion 1': 'Discussion 2', 
        'Directions': 'Directions 1', 
        'Eating': 'Eating 1',   
        'Eating 1': 'Eating', 
        'Greeting 1': 'Greeting',  
        'Greeting': 'Greeting 2',  
        'Phoning 1': 'Phoning 2', 
        'Phoning': 'Phoning 3', 
        'Posing': 'Posing 1', 
        'Posing 1': 'Posing', 
        'Purchases': 'Purchases 1', 
        'Purchases 1': 'Purchases', 
        'SittingDown 1': 'SittingDown 1', 
        'SittingDown': 'SittingDown',
        'Smoking': 'Smoking 2', 
        'Smoking 1': 'Smoking', 
        'Photo': 'Photo 1', 
        'Photo 1': 'Photo',
        'Waiting 1': 'Waiting',
        'Waiting': 'Waiting 1',
        'Walking 1': 'Walking', 
        'Walking': 'Walking 1', 
        'WalkDog': 'WalkDog 1', 
        'WalkDog 1': 'WalkDog', 
        'WalkTogether': 'WalkTogether 1',  
        'WalkTogether 1': 'WalkTogether', 
        'Sitting': 'Sitting 1' , 
        'Sitting 1': 'Sitting' 
    },
    'S9': {
        'Discussion': 'Discussion 1',  
        'Discussion 1': 'Discussion 2', 
        'Directions 1': 'Directions', 
        'Directions': 'Directions 1', 
        'Eating': 'Eating 1',   
        'Eating 1': 'Eating', 
        'Greeting': 'Greeting 1',  
        'Greeting 1': 'Greeting',  
        'Phoning': 'Phoning 1', 
        'Phoning 1': 'Phoning', 
        'Posing': 'Posing 1', 
        'Posing 1': 'Posing',  
        'Purchases': 'Purchases 1', 
        'Purchases 1': 'Purchases', 
        'SittingDown 1': 'SittingDown 1',
        'SittingDown': 'SittingDown', 
        'Smoking': 'Smoking 1',
        'Smoking 1': 'Smoking', 
        'Photo': 'Photo 1',  
        'Photo 1': 'Photo', 
        'Waiting 1': 'Waiting', 
        'Waiting': 'Waiting 1', 
        'Walking 1': 'Walking', 
        'Walking': 'Walking 1', 
        'WalkDog': 'WalkDog 1', 
        'WalkDog 1': 'WalkDog', 
        'WalkTogether': 'WalkTogether 1',  
        'WalkTogether 1': 'WalkTogether', 
        'Sitting': 'Sitting 1' , 
        'Sitting 1': 'Sitting' 
    },
    'S8': {
        'Discussion': 'Discussion 1', 
        'Discussion 1': 'Discussion',
        'Directions 1': 'Directions',  
        'Directions': 'Directions 1', 
        'Eating': 'Eating 1',  
        'Eating 1': 'Eating', 
        'Greeting': 'Greeting 1',   
        'Greeting 1': 'Greeting',
        'Phoning': 'Phoning 1', 
        'Phoning 1': 'Phoning', 
        'Posing': 'Posing 1', 
        'Posing 1': 'Posing',  
        'Purchases': 'Purchases 1', 
        'Purchases 1': 'Purchases', 
        'SittingDown 1': 'SittingDown 1',
        'SittingDown': 'SittingDown', 
        'Smoking': 'Smoking 1', 
        'Smoking 1': 'Smoking', 
        'Photo': 'Photo 1',  
        'Photo 1': 'Photo', 
        'Waiting 1': 'Waiting',
        'Waiting': 'Waiting 1', 
        'Walking 1': 'Walking', 
        'Walking': 'Walking 1', 
        'WalkDog': 'WalkDog 1', 
        'WalkDog 1': 'WalkDog', 
        'WalkTogether': 'WalkTogether 1', 
        'WalkTogether 1': 'WalkTogether 2',  
        'Sitting': 'Sitting 1' , 
        'Sitting 1': 'Sitting' 
    },
    'S7': {
        'Discussion': 'Discussion 1', 
        'Discussion 1': 'Discussion', 
        'Directions 1': 'Directions', 
        'Directions': 'Directions 1', 
        'Eating': 'Eating 1', 
        'Eating 1': 'Eating', 
        'Greeting': 'Greeting 1', 
        'Greeting 1': 'Greeting',
        'Phoning': 'Phoning 2', 
        'Phoning 1': 'Phoning',  
        'Posing': 'Posing 1',
        'Posing 1': 'Posing',  
        'Purchases': 'Purchases 1', 
        'Purchases 1': 'Purchases', 
        'SittingDown 1': 'SittingDown 1', 
        'SittingDown': 'SittingDown', 
        'Smoking': 'Smoking 1', 
        'Smoking 1': 'Smoking',
        'Photo 1': 'Photo 1',  
        'Photo': 'Photo', 
        'Waiting 1': 'Waiting 2', 
        'Waiting': 'Waiting 1', 
        'Walking 1': 'Walking 2', 
        'Walking': 'Walking 1', 
        'WalkDog': 'WalkDog 1', 
        'WalkDog 1': 'WalkDog', 
        'WalkTogether 1': 'WalkTogether', 
        'WalkTogether': 'WalkTogether 1', 
        'Sitting': 'Sitting 1' , 
        'Sitting 1': 'Sitting'
    },
    'S6': {
        'Discussion': 'Discussion 1',
        'Discussion 1': 'Discussion',
        'Directions 1': 'Directions', 
        'Directions': 'Directions 1', 
        'Eating': 'Eating 1', 
        'Eating 1': 'Eating 2', 
        'Greeting': 'Greeting 1', 
        'Greeting 1': 'Greeting', 
        'Phoning': 'Phoning 1', 
        'Phoning 1': 'Phoning', 
        'Posing': 'Posing 2', 
        'Posing 1': 'Posing', 
        'Purchases': 'Purchases 1',  
        'Purchases 1': 'Purchases', 
        'SittingDown': 'SittingDown 1', 
        'SittingDown 1': 'SittingDown', 
        'Smoking': 'Smoking 1', 
        'Smoking 1': 'Smoking', 
        'Photo 1': 'Photo 1',  
        'Photo': 'Photo', 
        'Waiting 1': 'Waiting', 
        'Waiting': 'Waiting 3', 
        'Walking': 'Walking 1', 
        'Walking 1': 'Walking', 
        'WalkDog': 'WalkDog 1', 
        'WalkDog 1': 'WalkDog', 
        'WalkTogether 1': 'WalkTogether',
        'WalkTogether': 'WalkTogether 1' ,
        'Sitting': 'Sitting 1' ,
        'Sitting 1': 'Sitting 2' 
    },
    'S1': {
        'Discussion': 'Discussion 1',
        'Discussion 1': 'Discussion',
        'Directions 1': 'Directions',
        'Directions': 'Directions 1',
        'Eating 2': 'Eating 2',
        'Eating': 'Eating',
        'Greeting': 'Greeting 1',
        'Greeting 1': 'Greeting',
        'Phoning': 'Phoning 1',
        'Phoning 1': 'Phoning',
        'Posing': 'Posing 1',
        'Posing 1': 'Posing',
        'Purchases': 'Purchases 1',
        'Purchases 1': 'Purchases',
        'SittingDown': 'SittingDown 2',
        'SittingDown 2': 'SittingDown',
        'Smoking': 'Smoking 1',
        'Smoking 1': 'Smoking',
        'Photo': 'Photo 1',
        'Photo 1': 'Photo',
        'Waiting 1': 'Waiting',
        'Waiting': 'Waiting 1',
        'Walking': 'Walking 1',
        'Walking 1': 'Walking',
        'WalkDog': 'WalkDog 1',
        'WalkDog 1': 'WalkDog',
        'WalkTogether 1': 'WalkTogether',
        'WalkTogether': 'WalkTogether 1',
        'Sitting': 'Sitting 1',
        'Sitting 2': 'Sitting 2'
    },
    'S5': {
        'Discussion': 'Discussion 2',
        'Discussion 1': 'Discussion 3',
        'Directions': 'Directions 1',
        'Directions 1': 'Directions 2',
        'Eating': 'Eating 1', 
        'Eating 1': 'Eating', 
        'Greeting': 'Greeting 1',  
        'Greeting 1': 'Greeting 2', 
        'Phoning': 'Phoning 1', 
        'Phoning 1': 'Phoning', 
        'Posing': 'Posing 1',
        'Posing 1': 'Posing', 
        'Purchases': 'Purchases 1', 
        'Purchases 1': 'Purchases', 
        'SittingDown 1': 'SittingDown 1', 
        'SittingDown': 'SittingDown', 
        'Smoking': 'Smoking 1', 
        'Smoking 1': 'Smoking', 
        'Photo 1': 'Photo 2', 
        'Photo': 'Photo', 
        'Waiting 1': 'Waiting 2', 
        'Waiting': 'Waiting 1', 
        'Walking': 'Walking 1', 
        'Walking 1': 'Walking', 
        'WalkDog': 'WalkDog 1',  
        'WalkDog 1': 'WalkDog', 
        'WalkTogether 1': 'WalkTogether', 
        'WalkTogether': 'WalkTogether 1',
        'Sitting 1': 'Sitting', 
        'Sitting': 'Sitting 1' 
    },
}